### ISSUE TITLE
I can't connect to my wordpress. com. 

### ISSUE THREAD

**Issue by OmaBeate** [meitar/wp-crosspost#2]
It just doesn't work and even my savy, techy friends can not connect it.
Can you tell me what is worng?
Beate

**Comment by nitishnarula** [comment]
I am not sure if @OmaBeate 's issue is the same but the plugin doesn't connect to my wordpress.com blog either.

I created an [application](https://developer.wordpress.com/apps/new) for my wordpress.com blog. Since I am using your [BYOC VM](https://maymay.net/blog/2014/03/13/bring-your-own-content-virtual-self-hosting-web-publishing/), these are the settings I chose when I created the application (the italicized descriptions are from wordpress application form):

**Website URL** (*The URL to an informational home page about your application*):
http://localhost:8080/wordpress

**Redirect URL** (*The URL we should redirect to during the authorization process*):
http://localhost:8080/wordpress/wp-admin/options-general.php?page=wp_crosspost_settings&wp_crosspost_callback

**Type**
Web (*clients must be able to keep the generated secret private and should do all authenticated API calls server to server*)


After that, I used the client I entered the Client ID and Client secret to WP Crossposter to the wordpress.com. The browser then redirects to wordpress.com 's oath2 site asking for permission to allow the application. I click Approve. Then it returns to the same Wordpress Crosspost Settings page where the client ID and OAuth consumer secret fields are available. 

When I start a new post, the Wordpress Crosspost box on the right sidebar is empty, showing no connection to my wordpress.com blog.

**Comment by OmaBeate** [comment]
I think the originator abandoned his plugin.

Be blessed
Beate

**Comment by meitar** [comment]
> I think the originator abandoned his plugin.

No, I just don't take action on issues that are not actionable. Obviously?

**Comment by fabacab** [comment]
> I created an application for my wordpress.com blog. Since I am using your [BYOC VM](https://maymay.net/blog/2014/03/13/bring-your-own-content-virtual-self-hosting-web-publishing/)…

I cannot reproduce this issue when using a vanilla hosting environment like Apache. BYOC has a different underlying setup, the problem may be localized to BYOC. If that's so, I'll continue discussing this issue at [fabacab/byoc](https://github.com/fabacab/byoc/) instead.

**Comment by meitar** [comment]
Okay, one possible problem is that the server on which WP-Crosspost is installed on does not have both the PHP cURL extension and the PHP OpenSSL extension installed, both of which are required. In some server set ups, WP-Crosspost does not give a good error message indicating that this is the issue, so be sure to check this on your hosting environment. I've added a note about this in the readme's "Installation notes and troubleshooting" section as of TK-commit.

If you're using BYOC, you should log in to the server and run:

```
sudo tazpkg get-install php-curl
sudo tazpkg get-install php-openssl
```

to make sure you have the required packages. I'll also be rev'ving the BYOC Vagrant box on HashiCorp Atlas with these packages pre-installed later tonight, so if you use the Vagrant version of BYOC you should just be able to `vagrant box update` to get the latest BYOC system build.
