### ISSUE TITLE
XML rpc / rest api not crossposting

### ISSUE THREAD

**Issue by papofrito** [meitar/wp-crosspost#5]
Hi!

I'm trying crosspost using the XML rpc wp api. I have a fresh wp 4.4.2 updated install, crossposting works when using the admin interface to create/update post, but firts attemps to update by wp XML rpc api only update my local wp local posts. I'm using SOAP UI for testing. Same result using the rest api (v2) and simple curl requests, local posts are updated, but not crossposted.

Thank you in advance,

Andréw

**Comment by meitar** [comment]
The WP Crosspost in the GUI creates a nonce that the plugin looks for. I'm guessing this nonce is missing from your XML-RPC and REST API calls. What happens if you delete these lines from the `savePost()` method:

```php
if (!isset($_POST[$this->prefix . '_meta_box_nonce']) || !wp_verify_nonce($_POST[$this->prefix . '_meta_box_nonce'], 'editing_' . $this->prefix)) {
            return;
        }
```

**Comment by papofrito** [comment]
What happens is that crossposting works, you are right :) I'll check wordpress doc to learn how to work with nonces with the api, maybe this is a good point to add to FAQ and "Other notes" sections at the plugin homepage. Thank you very much,

Andrés

**Comment by meitar** [comment]
If that's the problem then the mistake is my code, not yours. There's no way for an XML-RPC or REST API client to know the value of the plugin's nonce, so I need to either expose the correct nonce value in a place other than the graphical meta box or else I need to overload a different nonce (maybe there's a built-in WordPress one I can use in various contexts) for the test. But, hmm…it's possible that this is actually not required at all because maybe WordPress will take care of it. I have not worked with the XML-RPC or REST API quite as much so I don't know.

Can you tell me, when you use the APIs, do you need to send a nonce value with the request? If so, what does your request look like? This will help me figure out what the possible security consequences of removing the nonce would be. Thanks.

**Comment by papofrito** [comment]
In fact, there is no need for a nonce when doing api requests. I'm testing using basic authentication, i.e., I send the Basic header with a valid base64 encoded user:pass with all requests, which I supose is not an optimal approach, but it's a right way to do it, anyway. Regards,

Andrés

**Comment by meitar** [comment]
A WWW-Authenticate header is not a replacement for a nonce. The former is a user authentication scheme and the latter is a CSRF protection scheme. That's why I asked how you were sending the API requests; I want to know if WordPress requires a CSRF protection mechanism of its own so that I don't have to do it myself in the plugin. If WordPress does that, then great, I'll just use it. If not, then it's not safe to remove the nonce that WP Crosspost adds for itself.

**Comment by papofrito** [comment]
I'm being able to edit posts with both XML RPC and json apis, without sending the nonce in any request. For external apps, the wp rest api v2 guide [here](http://v2.wp-api.org/guide/authentication/) recommends OAuth authentication, basic authentication or application passwords. I'm using application passwords, a kind of basic auth without using the real user password. An example request:

curl --header "Authorization: Basic YWRUkdvAVzlsRiBwUD34hGFtTDIgdjEyYiBvY0NwIFpCem8=" -X POST -d "content=It works! (updated)" http://localhost/wp-json/wp/v2/posts/15
