### ISSUE TITLE
Crashed my server

### ISSUE THREAD

**Issue by yitzhak** [meitar/wp-crosspost#8]
Told it not to keep wordpress and wordpress.com in sync. It tried to do it anyway, and it crashed my server for 10 minutes. Fuck.

Server comes back online, and the first two posts are annotated. I wasn't expecting it to annotate the stuff that's actually on my server. Second blog down the list was annotated 150 times. And, coincidentally, I had about 150 copies of it that I now had to delete on the local server based wordpress, but not the remote wordpress.com wordpress. All featured images, including the one on the original copy of the post (as far as I can tell) were horked. Gone, or broken. 

During the same process, the system forgot which wordpress.com blog it was supposed to be syncing with, at least twice that I can tell. 

Dude, you seriously need to remove this thing from the Wordpress plugins list. If I had known how dangerous it was, or how much needless work it would have created for me this morning, I never would have installed it. It's nowhere near ready for prime time. 

Normal users, who don't have the experience I do with this kind of thing are libel to trash their whole websites with this plugin, and not know what to do. Leaving it in a place where the general public can use and download it is cruel and unreasonable.

This software is pre-alpha.

**Comment by meitar** [comment]
First of all,

> This software is pre-alpha.

That is what "version 0.4.2" implies, is it not? This is not a 1.0 release, not even close.

Secondly, you're reporting major problems that no one else has encountered, but you're not actually reporting them as bugs. This issue is the equivalent of "it didn't work for me."

Take a look at the plugin's support forum. There are users who have less technical skill than you but more skill in communicating about the problems they're experiencing.

You are welcome to submit an actual bug report, but otherwise, let me just say that, dude, you seriously need to remove yourself from GitHub.com.

**Comment by yitzhak** [comment]
It's responses like this, which are the reason I avoid generally contributing anything to open sources projects. Honestly, talking to you, or dealing with the fallout from this thing, is the absolute last thing I want to be doing.

If you can't be an adult and discuss this stuff rationally, well... I don't really know what to tell you, brother. It's your deal at that point, not mine.

There's a note in the plugin that the sync feature is experimental. There's nothing in it that says it's on whether you enable it or not. 

No note that says it'll start and never finish an infinite recursive loop that'll take down shared servers, or generate hundreds of garbage posts on the source server, which it will then attempt to sync mid cue. 

There's no warning there that says, don't sync with a remote site that's already been partially synced, even if the program has turned on sync without your knowledge.

The bug with the system forgetting which remote wordpress.com site is being talked to was already reported to someone else. You knew about that one. I mentioned it because it happened mid cue, which I thought was pertinent.

As the writer of the program, I have a hard time believing that you were unaware that it was annotating both local and remote sources. That would stretch credulity. 

If you choose to be offended by that, or this, that's your call. I don't really care. I was just trying to do my part to let you know something happened. 

Take care.

**Comment by meitar** [comment]
> It's responses like this, which are the reason I avoid generally contributing anything to open sources projects. Honestly, talking to you, or dealing with the fallout from this thing, is the absolute last thing I want to be doing.

If communicating about this is the last thing you want to be doing, I would suggest to you that perhaps you should not be doing it. If you choose to communicate about it, anyway, I will further suggest to you to do so with the requisite detail required to assist you. If you choose not to do that as well, then not only are you unlikely to receive the kind of response you want, but you're also actively contributing noise where signal is required.

Judging by the communication you've had with me so far, I can confidently say that [your lack of contributions to free software projects](https://web.archive.org/web/20160816012818/https://github.com/yitzhak?tab=activity) would be welcomed by most people volunteering to write free software.

My professional advice to you is to continue to use whatever free software you like, but refrain from "doing your part" until you are able to do so while adding a useful level of detail, or without the entitled attitude. Either/or is good enough for me, personally, but you'll get better results if you strive for both/and.

I don't believe you're capable of that, though, so I'll be happy if you simply never interact with me in any way again. If this plugin did indeed cause your server to crash, I'm frankly pleased that it was you, rather than someone who actually contributes useful things to free software and communicates with free software programmers respectfully, was the person afflicted by the trouble.
